from __future__ import annotations

from typing import Any


MEMORY_TOOL_NAMES = ["memory_search", "memory_recent", "memory_write"]
WEB_TOOL_NAMES = ["read_url", "summarize_url", "ask_url"]
SIMPLE_TOOL_NAMES = ["weather_get", "gold_get_price", "news_get", "search_web", "shortlink_create", "time_now"] + WEB_TOOL_NAMES
MEDIA_TOOL_NAMES = [
    "image_ocr",
    "image_describe",
    "image_extract_fields",
    "document_extract_text",
    "document_summarize",
    "document_search_answer",
    "document_extract_fields",
    "audio_transcribe",
    "audio_summarize",
    "video_transcribe",
    "video_summarize",
    "tts_speak",
]
CALENDAR_TOOL_NAMES = [
    "calendar_help",
    "calendar_list_today",
    "calendar_list_tomorrow",
    "calendar_find_event",
    "calendar_find_free_slot",
    "calendar_create_event",
    "calendar_reschedule_event",
    "calendar_delete_event",
    "calendar_check_availability",
]
GMAIL_TOOL_NAMES = [
    "gmail_help",
    "gmail_list_inbox",
    "gmail_read_email",
    "gmail_search_email",
    "gmail_search_by_sender",
    "gmail_send_email",
    "gmail_draft_email",
    "gmail_reply_email",
    "gmail_mark_read",
    "gmail_archive",
]
GITHUB_TOOL_NAMES = [
    "github_help",
    "github_list_user_repos",
    "github_search_repos",
    "github_get_repo",
    "github_get_repo_tree",
    "github_list_branches",
    "github_list_commits",
    "github_get_commit",
    "github_get_file",
    "github_search_code",
    "github_get_diff",
]
WORKSPACE_TOOL_NAMES = [
    "drive_help",
    "drive_list_files",
    "drive_search_file",
    "drive_get_file_info",
    "drive_create_folder",
    "drive_create_file",
    "drive_upload_file",
    "drive_download_file",
    "drive_share_file",
    "drive_move_file",
    "drive_rename_file",
    "drive_copy_file",
    "drive_delete_file",
    "drive_delete_folder",
    "drive_export_file",
    "docs_help",
    "docs_search_doc",
    "docs_read_doc",
    "docs_create_doc",
    "docs_append_doc",
    "docs_update_doc",
    "docs_delete_doc",
    "sheets_help",
    "sheets_search_sheet",
    "sheets_read_sheet",
    "sheets_read_range",
    "sheets_create_sheet",
    "sheets_append_row",
    "sheets_update_cell",
    "sheets_update_range",
    "sheets_delete_sheet",
]
GOOGLE_FULL_TOOL_NAMES = CALENDAR_TOOL_NAMES + GMAIL_TOOL_NAMES + WORKSPACE_TOOL_NAMES

AGENT_TOOLSETS: dict[str, list[str]] = {
    "general": MEMORY_TOOL_NAMES + SIMPLE_TOOL_NAMES,
    "media": MEMORY_TOOL_NAMES + MEDIA_TOOL_NAMES,
    "calendar": MEMORY_TOOL_NAMES + CALENDAR_TOOL_NAMES,
    "gmail": MEMORY_TOOL_NAMES + GMAIL_TOOL_NAMES,
    "github": MEMORY_TOOL_NAMES + GITHUB_TOOL_NAMES,
    "workspace": MEMORY_TOOL_NAMES + WORKSPACE_TOOL_NAMES,
    "google_full": MEMORY_TOOL_NAMES + GOOGLE_FULL_TOOL_NAMES,
}

DIRECT_GATEWAY_TOOLS: dict[str, str] = {
    "weather_get": "weather.get",
    "gold_get_price": "gold.get_price",
    "news_get": "news.get",
    "search_web": "search.web",
    "read_url": "web.read_url",
    "summarize_url": "web.summarize_url",
    "shortlink_create": "shortlink.create",
    "image_ocr": "media.image_ocr",
    "image_describe": "media.image_describe",
    "image_extract_fields": "media.image_extract_fields",
    "document_extract_text": "media.document_extract_text",
    "document_summarize": "media.document_summarize",
    "document_search_answer": "media.document_search_answer",
    "document_extract_fields": "media.document_extract_fields",
    "audio_transcribe": "media.audio_transcribe",
    "audio_summarize": "media.audio_summarize",
    "video_transcribe": "media.video_transcribe",
    "video_summarize": "media.video_summarize",
    "tts_speak": "media.tts_speak",
    "calendar_help": "calendar.help",
    "calendar_list_today": "calendar.list_today",
    "calendar_list_tomorrow": "calendar.list_tomorrow",
    "calendar_find_event": "calendar.find_event",
    "calendar_create_event": "calendar.create_event",
    "calendar_delete_event": "calendar.delete_event",
    "calendar_check_availability": "calendar.check_availability",
    "calendar_find_free_slot": "calendar.find_free_slot",
    "gmail_help": "gmail.help",
    "gmail_list_inbox": "gmail.list_inbox",
    "gmail_read_email": "gmail.read_email",
    "gmail_search_email": "gmail.search_email",
    "gmail_search_by_sender": "gmail.search_by_sender",
    "gmail_send_email": "gmail.send_email",
    "gmail_draft_email": "gmail.draft_email",
    "gmail_reply_email": "gmail.reply_email",
    "gmail_mark_read": "gmail.mark_read",
    "gmail_archive": "gmail.archive",
    "github_help": "github.help",
    "github_list_user_repos": "github.list_user_repos",
    "github_search_repos": "github.search_repos",
    "github_get_repo": "github.get_repo",
    "github_get_repo_tree": "github.get_repo_tree",
    "github_list_branches": "github.list_branches",
    "github_list_commits": "github.list_commits",
    "github_get_commit": "github.get_commit",
    "github_get_file": "github.get_file",
    "github_search_code": "github.search_code",
    "github_get_diff": "github.get_diff",
    "drive_help": "drive.help",
    "drive_list_files": "drive.list_files",
    "drive_search_file": "drive.search_file",
    "drive_get_file_info": "drive.get_file_info",
    "drive_create_folder": "drive.create_folder",
    "drive_create_file": "drive.create_file",
    "drive_upload_file": "drive.upload_file",
    "drive_download_file": "drive.download_file",
    "drive_share_file": "drive.share_file",
    "drive_move_file": "drive.move_file",
    "drive_rename_file": "drive.rename_file",
    "drive_copy_file": "drive.copy_file",
    "drive_delete_file": "drive.delete_file",
    "drive_delete_folder": "drive.delete_folder",
    "drive_export_file": "drive.export_file",
    "docs_help": "docs.help",
    "docs_search_doc": "docs.search_doc",
    "docs_read_doc": "docs.read_doc",
    "docs_create_doc": "docs.create_doc",
    "docs_append_doc": "docs.append_doc",
    "docs_update_doc": "docs.update_doc",
    "docs_delete_doc": "docs.delete_doc",
    "sheets_help": "sheets.help",
    "sheets_search_sheet": "sheets.search_sheet",
    "sheets_read_sheet": "sheets.read_sheet",
    "sheets_read_range": "sheets.read_sheet",
    "sheets_create_sheet": "sheets.create_sheet",
    "sheets_append_row": "sheets.append_row",
    "sheets_update_cell": "sheets.update_cell",
    "sheets_update_range": "sheets.update_range",
    "sheets_delete_sheet": "sheets.delete_sheet",
}

DIRECT_TOOL_DEFAULT_ARGS: dict[str, dict[str, Any]] = {
    "drive_list_files": {"limit": 3},
    "drive_search_file": {"limit": 3},
    "docs_search_doc": {"limit": 3},
    "sheets_search_sheet": {"limit": 3},
    "github_list_branches": {"limit": 20},
    "github_list_commits": {"limit": 20},
    "github_search_code": {"limit": 10},
    "github_list_user_repos": {"limit": 20},
    "github_search_repos": {"limit": 10},
    "github_get_repo_tree": {"limit": 20},
}

DIRECT_ROUTE_TOOLS = set(DIRECT_GATEWAY_TOOLS) | {"memory_recent", "time_now"}

# Read-only / low-side-effect capabilities that should stay on the cheap path
# even when users append style instructions like "rồi tóm tắt ngắn".
DETERMINISTIC_DIRECT_TOOLS = {
    "memory_recent",
    "weather_get",
    "gold_get_price",
    "news_get",
    "search_web",
    "read_url",
    "summarize_url",
    "shortlink_create",
    "time_now",
    "image_ocr",
    "image_describe",
    "image_extract_fields",
    "document_extract_text",
    "document_summarize",
    "document_search_answer",
    "document_extract_fields",
    "audio_transcribe",
    "audio_summarize",
    "video_transcribe",
    "video_summarize",
    "tts_speak",
    "calendar_help",
    "calendar_list_today",
    "calendar_list_tomorrow",
    "calendar_find_free_slot",
    "gmail_help",
    "gmail_list_inbox",
    "github_help",
    "github_list_user_repos",
    "github_search_repos",
    "github_get_repo",
    "github_get_repo_tree",
    "github_list_branches",
    "github_list_commits",
    "github_get_commit",
    "github_get_file",
    "github_search_code",
    "github_get_diff",
    "drive_help",
    "docs_help",
    "sheets_help",
    "image_ocr",
    "document_extract_text",
    "audio_transcribe",
    "video_transcribe",
    "tts_speak",
    "gmail_search_by_sender",
    "sheets_read_range",
}

DIRECT_FRIENDLY_MULTISTEP_TOOLS = set(DETERMINISTIC_DIRECT_TOOLS)


def build_capability_overview_text() -> str:
    return "\n".join(
        [
            "Hiện tại Mia có thể làm những nhóm việc sau:",
            "1. Thời tiết, giá vàng, tin tức, tìm kiếm web, đọc link, tóm tắt link, hỏi tiếp link và tạo shortlink.",
            "2. Nhớ thông tin qua memory.",
            "3. Ảnh: đọc chữ, mô tả ảnh, trích thông tin từ ảnh.",
            "4. Tài liệu: trích text, tóm tắt, hỏi đáp, trích trường dữ liệu từ PDF/Word/TXT.",
            "5. Âm thanh và video: chép lời và tóm tắt.",
            "6. Gmail: xem hộp thư, đọc mail, tìm mail, soạn mail, gửi mail, trả lời mail.",
            "7. Google Calendar: xem lịch, tìm sự kiện, tạo lịch, huỷ lịch, kiểm tra giờ rảnh.",
            "8. Google Drive: xem file, tìm file, xem thông tin file, tạo folder/file, upload, download, chia sẻ, đổi tên, di chuyển, copy, xoá, export.",
            "9. Google Docs: tìm doc, đọc doc, tạo doc, thêm nội dung, xoá doc.",
            "10. Google Sheets: tìm sheet, đọc sheet, tạo sheet, thêm dòng, cập nhật ô, xoá sheet.",
            "11. GitHub (read-only): xem repo của anh, xem cấu trúc repo, liệt kê repo trong account, tìm repo theo topic/ngôn ngữ, liệt kê branch, xem lịch sử commit, xem chi tiết commit, đọc file, tìm code trong repo, xem diff.",
            "12. Một số thao tác mới đã có sẵn: Gmail theo người gửi, đánh dấu đã đọc, lưu trữ mail; Calendar tìm khung giờ trống và dời lịch; Docs cập nhật nội dung; Sheets đọc/cập nhật vùng dữ liệu.",
            "13. Web: đọc trực tiếp link cụ thể, tóm tắt link cụ thể và hỏi tiếp trên link đã đọc hoặc vừa tóm tắt.",
            "",
            "Nếu anh Minh muốn, Mia có thể nói riêng từng nhóm hoặc đưa ví dụ câu lệnh cho từng tool.",
        ]
    )
